apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: facilgo-capex-assist-portal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nkoppala-facilgo/argocd.git
    targetRevision: main
    path: test/
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
  # hooks:
  #   - name: send-slack-notification
  #     sync:
  #       automated: 
  #         post:
  #           - command: ["/bin/sh", "-c"]
  #             args:
  #               - ./send_slack_message.sh